runtime: python310

entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

env_variables:
  FLASK_APP: "main.py"
  SECRET_KEY: "fhX7tG9yZN2w8kL5vQ3pP6mD1rJ4sA0uB9cE2xF3"
  GCS_BUCKET_NAME: "encoded-shape-452012-k8-secure-downloads"
  
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65
